theme: 'PaperMod'
baseURL: http://blog.infamous55.com/
languageCode: en-us
title: infamous55's blog

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: tags

params:
  env: production
  title: infamous55's blog
  # description: "ExampleSite description"
  # keywords: [Blog, Portfolio, PaperMod]
  author: infamous55
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: '2 January, 2006'
  defaultTheme: dark
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: '/favicon.ico'
    favicon16x16: '/favicon-16x16.png'
    favicon32x32: '/favicon-32x32.png'
    apple_touch_icon: '/apple-touch-icon.png'
    safari_pinned_tab: '/safari-pinned-tab.svg'

  label:
    text: 'infamous55'

  # home-info mode
  homeInfoParams:
    Title: 'Hi there! 👋'
    Content: "I'm infamous55, and this is where I share what I learn about various topics in software development, devops, and cybersecurity. Thanks for stopping by!"

  socialIcons:
    - name: github
      url: 'https://github.com/infamous55'
    - name: mastodon
      url: 'https://infosec.exchange/@alreadydeadxd/'
    - name: other
      title: personal
      url: 'https://infamous55.com/'

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

menu:
  main:
    - identifier: archive
      name: archive
      url: /archive/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weigth: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#   highlight:
#     noClasses: false
#     anchorLineNos: true
#     codeFences: true
#     guessSyntax: true
#     lineNos: false
#     style: monokai

# for search
outputs:
  home:
    - HTML
    - RSS
    - JSON
